language: php
php:
  - '7.4'

before_script:
  - composer install

script:
  - find . -name '*.php' -exec php -l {} \;
  - vendor/bin/phpstan analyse --level=5 --no-progress *.php
  - vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md --ignore=vendor/ .
